name: C/C++ CI 

on: [push]

jobs:
  check-bitops:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          cd 02struct
          make bitops
          bitops 94140480 101100111000111100000111111 > bitops.test
          diff bitops.test bitops.check
      
